#!/bin/sh
set -e -u
version=${1:?"no version number provided"}
PS4='$ '
set -x
dch -m -v "$version" -u low -c doc/changelog
sed -i -r -e "s/^(__version__) = '[0-9.]+'$/\1 = '$version'/" lib/version.py
sed -i -r -e "s/<(!ENTITY version) '[0-9.]+'>/<\1 '$version'>/" doc/*.xml
